// SPDX-License-Identifier: Apache-2.0
import Foundation
import PackagePlugin

@main
struct VersionPlugin: BuildToolPlugin {
    // SPM's build command cache is keyed on `inputFiles`: the command only
    // re-runs when one of those paths is newer than its declared output.
    // The previous incarnation declared `inputFiles: []`, which meant
    // "nothing invalidates this output" — once Version.swift existed SPM
    // never regenerated it, so `VERSION` froze at whatever git state the
    // first build saw regardless of later commits, branch switches, or
    // `SIM_USE_VERSION` changes. A stale stamp also undermines the daemon
    // version-check gate added in LINEIOS-216319.
    //
    // Fix: list every source file the target compiles as inputs. Any
    // edit, branch switch, or checkout that shifts a `.swift` file's
    // mtime now invalidates the cached Version.swift and triggers a
    // fresh `git describe`. Downstream recompile only fires when the
    // generated content actually changes, so the incremental-build
    // overhead is bounded to one subprocess per real source edit.
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let outputPath = context.pluginWorkDirectory.appending("Version.swift")

        let inputFiles: [Path] = target.sourceModule?.sourceFiles
            .filter { $0.type == .source }
            .map(\.path) ?? []

        return [
            .buildCommand(
                displayName: "Generate Version.swift",
                executable: .init("/usr/bin/env"),
                arguments: [
                    "swift", "-e",
                    """
                    import Foundation

                    func getVersion() -> String {
                        // Priority 1: Environment variable (CI)
                        if let envVersion = ProcessInfo.processInfo.environment["SIM_USE_VERSION"] {
                            return envVersion
                        }

                        // Priority 2: Git describe (local development)
                        let gitProcess = Process()
                        gitProcess.executableURL = URL(fileURLWithPath: "/usr/bin/git")
                        gitProcess.arguments = ["describe", "--tags", "--always", "--dirty"]

                        let pipe = Pipe()
                        gitProcess.standardOutput = pipe
                        gitProcess.standardError = Pipe()

                        do {
                            try gitProcess.run()
                            gitProcess.waitUntilExit()

                            if gitProcess.terminationStatus == 0 {
                                let data = pipe.fileHandleForReading.readDataToEndOfFile()
                                if let version = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) {
                                    return version.isEmpty ? "dev" : version
                                }
                            }
                        } catch {
                            // Git command failed
                        }

                        // Priority 3: Fallback
                        return "dev"
                    }

                    let version = getVersion()
                    let content = "// Auto-generated by VersionPlugin\\nlet VERSION = \\"\\(version)\\""

                    try content.write(toFile: "\\(CommandLine.arguments[1])", atomically: true, encoding: .utf8)
                    """,
                    outputPath.string,
                ],
                environment: [:],
                inputFiles: inputFiles,
                outputFiles: [outputPath]
            ),
        ]
    }
}