// swift-tools-version:5.10
// SPDX-License-Identifier: Apache-2.0
import PackageDescription

// The SwiftBuild-backend SwiftPM (Xcode 26.6+/27 toolchains) emits no
// LC_RPATH entries for binary-target XCFrameworks, so the sim-use binary
// and the SimUseTests bundle cannot dlopen the FB* frameworks that
// `scripts/build.sh` places under build_products/. Emit explicit rpath
// entries pointing at each XCFramework slice: `@loader_path`-relative for
// the known product layouts (classic `.build/<arch>/<config>` and
// SwiftBuild `.build/out/Products/<config>`), plus a working-directory
// relative fallback for custom `--scratch-path` runs started from the
// repository root. dyld ignores entries that do not resolve, and the
// classic-toolchain layouts keep working through their own rpaths.
let fbFrameworkSliceDirs = [
    "FBControlCore", "FBSimulatorControl", "FBDeviceControl", "XCTestBootstrap",
].map { "build_products/XCFrameworks/\($0).xcframework/macos-arm64_x86_64" }

// upLevels: how many directories separate the linked product from the
// repository root (per supported layout).
func fbRPathFlags(upLevels: [Int]) -> [String] {
    fbFrameworkSliceDirs.flatMap { slice -> [String] in
        let entries = upLevels.map { up in
            "@loader_path/" + String(repeating: "../", count: up) + slice
        } + [slice]
        return entries.flatMap { ["-Xlinker", "-rpath", "-Xlinker", $0] }
    }
}

let package = Package(
    name: "SimUse",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(
            name: "sim-use",
            targets: ["SimUse"]
        ),
        .library(
            name: "SimUseCore",
            targets: ["SimUseCore"]
        ),
        .library(
            name: "AndroidBackend",
            targets: ["AndroidBackend"]
        ),
        .library(
            name: "iOSSimBackend",
            targets: ["iOSSimBackend"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.5.0"),
    ],
    targets: [
        .target(
            name: "SimUseCore",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/SimUseCore",
            // VERSION is consumed by the daemon (DaemonClient version-
            // check gate, DaemonServer ping response). Generating it
            // per-target is cheap and keeps the daemon dependency-free
            // of higher targets.
            plugins: ["VersionPlugin"]
        ),
        .target(
            name: "iOSSimBackend",
            dependencies: [
                "SimUseCore",
                "FBSimulatorControl",
                "FBDeviceControl",
                "FBControlCore",
                "XCTestBootstrap",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/iOSSimBackend",
            // No `-rpath` here: the executable `SimUse` target owns
            // `@executable_path` at link time, and ld emits a
            // "duplicate -rpath ignored" warning when both targets
            // claim it. Library targets don't load XCFrameworks; only
            // the final executable needs the runtime search path.
            plugins: ["VersionPlugin"]
        ),
        .target(
            name: "AndroidBackend",
            dependencies: [
                "SimUseCore",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/AndroidBackend",
            // Resources/ holds `sim-use-device-bridge.apk` at runtime
            // (built by `scripts/build-bridge.sh`). Copy the whole
            // directory so the SPM build doesn't require the APK to
            // exist at build time — `AndroidDeviceController` surfaces
            // a clear "Bridge APK not found" error when the resource
            // is missing.
            resources: [
                .copy("Resources"),
            ]
        ),
        .executableTarget(
            name: "SimUse",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                "SimUseCore",
                "AndroidBackend",
                "iOSSimBackend",
                "FBSimulatorControl",
                "FBDeviceControl",
                "FBControlCore",
                "XCTestBootstrap"
            ],
            path: "Sources/SimUse",
            resources: [
                .copy("Resources/skills"),
                // Built Viewer SPA assets (Vite output). Re-generated by
                // `scripts/build-viewer.sh`; committed so `swift build`
                // works without Node on contributor machines that don't
                // touch the Viewer. The `viewer` subcommand reads this
                // tree via `Bundle.module.resourceURL` and serves it
                // out of a local HTTP listener.
                .copy("Resources/viewer"),
            ],
            swiftSettings: [
                .unsafeFlags(["-parse-as-library"])
            ],
            linkerSettings: [
                // For XCFrameworks, rpath can often be just @executable_path
                // if SPM handles embedding correctly, or you might need to adjust
                // if you manually copy them later for distribution.
                // The executable sits 3 (classic) or 4 (SwiftBuild) levels
                // below the repository root.
                .unsafeFlags([
                    "-Xlinker", "-dead_strip",
                    "-Xlinker", "-headerpad_max_install_names",
                    "-Xlinker", "-rpath", "-Xlinker", "@executable_path" // Simpler rpath for SPM-handled XCFrameworks
                ] + fbRPathFlags(upLevels: [3, 4]))
            ],
            plugins: ["VersionPlugin"]
        ),
        .testTarget(
            name: "SimUseTests",
            dependencies: ["SimUse", "iOSSimBackend", "SimUseCore"],
            path: "Tests",
            // `Tests/` is the umbrella path; the sub-target test
            // directories below sit under it as separate testTargets.
            // List them by name in `exclude` so SwiftPM doesn't double-
            // claim their sources. Add new test sub-directories here
            // when adding new testTargets, or move them out from under
            // `Tests/` to drop this maintenance burden.
            exclude: [
                "SimUseCoreTests",
                "AndroidBackendTests",
            ],
            resources: [
                .copy("README.md"),
                .copy("Fixtures")
            ],
            linkerSettings: [
                // The test bundle binary sits 6 (classic) or 7 (SwiftBuild)
                // levels below the repository root
                // (…/SimUseTests.xctest/Contents/MacOS/SimUseTests).
                .unsafeFlags(fbRPathFlags(upLevels: [6, 7]))
            ]
        ),
        .testTarget(
            name: "SimUseCoreTests",
            dependencies: ["SimUseCore"],
            path: "Tests/SimUseCoreTests"
        ),
        .testTarget(
            name: "AndroidBackendTests",
            dependencies: ["AndroidBackend", "SimUseCore"],
            path: "Tests/AndroidBackendTests"
            // `Fixtures/` here is empty (`.gitkeep` only) — listing
            // it as a resource would emit a SwiftPM warning. Add a
            // `.copy("Fixtures")` entry when real fixture files
            // land.
        ),
        .plugin(
            name: "VersionPlugin",
            capability: .buildTool(),
            path: "Plugins/VersionPlugin"
        ),
        .binaryTarget(
            name: "FBControlCore",
            path: "build_products/XCFrameworks/FBControlCore.xcframework"
        ),
        .binaryTarget(
            name: "FBDeviceControl",
            path: "build_products/XCFrameworks/FBDeviceControl.xcframework"
        ),
        .binaryTarget(
            name: "FBSimulatorControl",
            path: "build_products/XCFrameworks/FBSimulatorControl.xcframework"
        ),
        .binaryTarget(
            name: "XCTestBootstrap",
            path: "build_products/XCFrameworks/XCTestBootstrap.xcframework"
        ),
    ]
)
